services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" # Porta para a API
      - "9001:9001" # Porta para a Web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data # Persistência de dados
    command: server /data --console-address ":9001"
    restart: always

  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse
    platform: linux/amd64/v8
    ports:
      - "8123:8123" # Porta para a HTTP interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse # Persistência de dados
      - ./clickhouse-users.xml:/etc/clickhouse-server/users.xml # Configuração de usuários
    restart: always
    networks:
      - clickhouse_network

  # cosmetic-coders-api: # Move this service out of clickhouse section
  #   image: cosmetic-coders-api:latest
  #   container_name: cosmetic-coders-api
  #   ports:
  #     - "5500:5500"
  #   environment:
  #     - MINIO_ROOT_USER=${MINIO_ROOT_USER}
  #     - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
  #     - MINIO_ENDPOINT=${MINIO_ENDPOINT}
  #     - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
  #     - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
  #     - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
  #     - CLICKHOUSE_PORT=${CLICKHOUSE_PORT}
  #     - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
  #     - DATABASE_URL=${DATABASE_URL}
  #     - SUPABASE_URL=${SUPABASE_URL}
  #     - SUPABASE_KEY=${SUPABASE_KEY}
  #     - SECRET_KEY_AWS=${SECRET_KEY_AWS}
  #     - SESSION_TOKEN_AWS=${SESSION_TOKEN_AWS}
  #     - ACCESS_KEY_AWS=${ACCESS_KEY_AWS}
  #   networks:
  #     - clickhouse_network

volumes:
  minio_data:
  clickhouse_data:

networks:
  clickhouse_network:
