name: Build and Push Docker Images to ECR

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the pipeline on'
        required: true
        default: 'main'  # Branch padrão

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}  # Usa a branch de input do usuário

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image 1
        env:
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          # Caminho do Dockerfile 1
          DOCKERFILE_PATH=./src/api  # Substitua pelo caminho correto

          # Obtém o URI do repositório ECR 1
          REPOSITORY_URI=$(aws ecr describe-repositories --repository-names $ECR_REPOSITORY --region $AWS_REGION --query 'repositories[0].repositoryUri' --output text)
          
          # Constrói a imagem Docker 1 especificando o caminho do Dockerfile
          docker build -t $REPOSITORY_URI:latest -f $DOCKERFILE_PATH/Dockerfile $DOCKERFILE_PATH
          
          # Faz o push da imagem para o ECR 1
          docker push $REPOSITORY_URI:latest
